"""Initial schema

Revision ID: 3ae598c7c650
Revises: 
Create Date: 2025-12-18 21:41:50.661750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae598c7c650'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_cache',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('game_metadata', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_index(op.f('ix_catalog_cache_appid'), 'catalog_cache', ['appid'], unique=False)
    op.create_table('users',
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_steam_id', sa.BigInteger(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('recommendation_mode', sa.String(length=50), nullable=True),
    sa.Column('score_at_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_steam_id'], ['users.steam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_action', 'feedback', ['action'], unique=False)
    op.create_index(op.f('ix_feedback_appid'), 'feedback', ['appid'], unique=False)
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index('ix_feedback_user_appid', 'feedback', ['user_steam_id', 'appid'], unique=False)
    op.create_index(op.f('ix_feedback_user_steam_id'), 'feedback', ['user_steam_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_steam_id', sa.BigInteger(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('recommendation_mode', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('content_score', sa.Float(), nullable=True),
    sa.Column('preference_score', sa.Float(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_steam_id'], ['users.steam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_appid'), 'recommendations', ['appid'], unique=False)
    op.create_index('ix_recommendations_generated_at', 'recommendations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index('ix_recommendations_user_mode', 'recommendations', ['user_steam_id', 'recommendation_mode'], unique=False)
    op.create_index(op.f('ix_recommendations_user_steam_id'), 'recommendations', ['user_steam_id'], unique=False)
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_steam_id', sa.BigInteger(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('playtime_hours', sa.Float(), nullable=False),
    sa.Column('playtime_category', sa.String(length=50), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_steam_id'], ['users.steam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_steam_id', 'appid', name='uq_user_game')
    )
    op.create_index(op.f('ix_user_games_appid'), 'user_games', ['appid'], unique=False)
    op.create_index(op.f('ix_user_games_id'), 'user_games', ['id'], unique=False)
    op.create_index('ix_user_games_user_appid', 'user_games', ['user_steam_id', 'appid'], unique=False)
    op.create_index(op.f('ix_user_games_user_steam_id'), 'user_games', ['user_steam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_games_user_steam_id'), table_name='user_games')
    op.drop_index('ix_user_games_user_appid', table_name='user_games')
    op.drop_index(op.f('ix_user_games_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_appid'), table_name='user_games')
    op.drop_table('user_games')
    op.drop_index(op.f('ix_recommendations_user_steam_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_user_mode', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_generated_at', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_appid'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_feedback_user_steam_id'), table_name='feedback')
    op.drop_index('ix_feedback_user_appid', table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_index(op.f('ix_feedback_appid'), table_name='feedback')
    op.drop_index('ix_feedback_action', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_catalog_cache_appid'), table_name='catalog_cache')
    op.drop_table('catalog_cache')
    # ### end Alembic commands ###
